
language: node_js

node_js:
  - "6"
  - "8"
  - "10"

sudo: false

cache:
  directories:
    - "node_modules"

script:
  - npm run test:coverage

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
