
language: node_js

node_js:
  - "10"
  - "12"
  - "14"
  - "16"

sudo: false

cache:
  directories:
    - "node_modules"

script:
  - npm run test:coverage

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
